# Se stiamo usando MetalLB la prima volta va fatto helmfile sync e non apply, altrimenti fallisce la creazione delle CRD del chart my-infrastructure

repositories:
  # - name: prometheus-community
  #   url: https://prometheus-community.github.io/helm-charts
  # - name: grafana
  #   url: https://grafana.github.io/helm-charts
  # - name: jaegertracing
  #   url: https://jaegertracing.github.io/helm-charts
  # - name: bitnami
  #   url: https://charts.bitnami.com/bitnami
  # - name: longhorn
  #   url: https://charts.longhorn.io
  # - name: opentelemetry
  #   url: https://open-telemetry.github.io/opentelemetry-helm-charts
  # - name: istio
  #   url: https://istio-release.storage.googleapis.com/charts
  # - name: kiali
  #   url: https://kiali.org/helm-charts
  # - name: ingress-nginx
  #   url: https://kubernetes.github.io/ingress-nginx
  # - name: metallb
  #   url: https://metallb.github.io/metallb
  # - name: datadog
  #   url: https://helm.datadoghq.com
  # - name: cetic #apache nifi
  #   url: https://cetic.github.io/helm-charts
  # - name: camunda
  #   url: https://helm.camunda.io
  # - name: apache-tika
  #   url: https://apache.jfrog.io/artifactory/tika

environments:
  default:
    values:
    - values.yaml.gotmpl

releases:

# NON USARE SU MINIKUBE, NON LO FA NEMMENO CANCELLARE SE NO
#   - name: longhorn
#     namespace: longhorn-system
#     chart: longhorn/longhorn
#     version: 1.7.0
#     installed: {{ .Values.installed.longhorn }}
#     values:
#       - longhorn-values.yaml

  # - name: kube-prometheus-stack
  #   namespace: monitoring
  #   chart: prometheus-community/kube-prometheus-stack
  #   version: 62.3.0
  #   disableValidation: true
  #   installed: {{ .Values.installed.prometheusStack }}
  #   values:
  #     - kube-prometheus-stack-values.yaml.gotmpl
  #   {{- if .Values.installed.longhorn }}
  #   needs:
  #     - longhorn-system/longhorn
  #   {{- end }}

#   - name: loki-stack
#     namespace: logging
#     chart: grafana/loki-stack
#     version: 2.10.0
#     installed: {{ .Values.installed.loki }}
#     values:
#       - loki-stack-values.yaml.gotmpl
#     {{- if .Values.installed.longhorn }}
#     needs:
#       - longhorn-system/longhorn
#     {{- end }}

#   - name: jaeger
#     namespace: tracing
#     chart: jaegertracing/jaeger
#     version: 3.2.0
#     installed: {{ .Values.installed.jaeger }}
#     values:
#       - jaeger-values.yaml
#     {{- if .Values.installed.longhorn }}
#     needs:
#       - longhorn-system/longhorn
#     {{- end }}

#   - name: opentelemetry-collector
#     namespace: tracing
#     chart: opentelemetry/opentelemetry-collector
#     version: 0.104.0
#     installed: {{ and .Values.installed.jaeger .Values.installed.opentelemetry }}
#     values:
#       - opentelemetry-collector-values.yaml
#     needs:
#       - tracing/jaeger

#   - name: rabbitmq
#     namespace: messaging
#     chart: bitnami/rabbitmq
#     version: 14.6.0
#     installed: {{ .Values.installed.rabbitMQ }}
#     values:
#       - rabbitmq-values.yaml.gotmpl
#     {{- if .Values.installed.longhorn }}
#     needs:
#       - longhorn-system/longhorn
#     {{- end }}

#   - name: redis
#     namespace: cache
#     chart: bitnami/redis
#     version: 20.0.0
#     installed: {{ .Values.installed.redis }}
#     values:
#       - redis-values.yaml

#   - name: mongodb
#     namespace: database
#     chart: bitnami/mongodb
#     version: 15.6.0
#     installed: {{ .Values.installed.mongoDB }}
#     values:
#       - mongodb-values.yaml.gotmpl
#     {{- if .Values.installed.longhorn }}
#     needs:
#       - longhorn-system/longhorn
#     {{- end }}

#   - name: istio-base
#     namespace: istio-system
#     chart: istio/base
#     version: 1.23.0
#     installed: {{ .Values.installed.istio }}
#     values:
#       - istio-base-values.yaml

#   - name: istiod
#     namespace: istio-system
#     chart: istio/istiod
#     version: 1.23.0
#     installed: {{ .Values.installed.istio }}
#     values:
#       - istiod-values.yaml
#     needs:
#       - istio-base

#   - name: kiali-operator
#     namespace: kiali-operator
#     chart: kiali/kiali-operator
#     disableValidation: true
#     version: 1.89.0
#     installed: {{ and .Values.installed.istio .Values.installed.kiali }}
#     values:
#       - kiali-operator-values.yaml
#     needs:
#       - istio-system/istiod

  # - name: ingress-nginx
  #   namespace: ingress-nginx
  #   chart: ingress-nginx/ingress-nginx
  #   version: 4.11.2 
  #   installed: {{ .Values.installed.ingressNginx }}

#   - name: metallb
#     namespace: metallb-system
#     chart: metallb/metallb
#     version: 0.14.8
#     installed: {{ .Values.installed.metalLB }}
#     wait: true #altrimenti fallisce la creazione di my-infrastructure

# #chart usato per creare i CRD di metalLB al cluster, serve per gli indirizzi IP dei LoadBalancers
#   - name: my-infrastructure
#     # namespace: metallb-system
#     chart: ./my-infrastructure
#     installed: {{ or .Values.installed.metalLB .Values.installed.datadog }}
#     needs:
#       {{- if .Values.installed.metalLB }}
#       - metallb-system/metallb
#       {{- end }}
#       {{- if .Values.installed.datadog }}
#       - datadog/datadog-operator
#       {{- end }}
#     values:
#       - it-infrastructure-values.yaml.gotmpl

  - name: minio
    namespace: minio
    chart: bitnami/minio
    version: 14.7.16
    installed: {{ .Values.installed.minio }}
    values:
      - minio-values.yaml.gotmpl
    {{- if .Values.installed.longhorn }}
    needs:
      - longhorn-system/longhorn
    {{- end }}

  # - name: datadog-operator
  #   namespace: datadog
  #   chart: datadog/datadog-operator
  #   version: 2.1.0
  #   createNamespace: true
  #   installed: {{ .Values.installed.datadog }}

  # - name: apache-nifi
  #   namespace: nifi
  #   chart: cetic/nifi
  #   version: 1.2.1
  #   createNamespace: true
  #   installed: {{ .Values.installed.nifi }}
  #   values:
  #     - nifi-values.yaml.gotmpl
  #   {{- if .Values.installed.longhorn }}
  #   needs:
  #     - longhorn-system/longhorn
  #   {{- end }}

  # - name: camunda
  #   namespace: camunda
  #   chart: camunda/camunda-platform
  #   createNamespace: true
  #   installed: {{ .Values.installed.camunda }}
  #   values:
  #     - camunda-values.yaml.gotmpl
  #   {{- if .Values.installed.longhorn }}
  #   needs:
  #     - longhorn-system/longhorn
  #   {{- end }}

  # - name: tika
  #   namespace: tika
  #   chart: apache-tika/tika
  #   version: 2.9.0
  #   createNamespace: true
  #   installed: {{ .Values.installed.tika }}
  #   values:
  #     - tika-values.yaml