# templates/secrets.yaml
{{- if .Values.gitlab }}
apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secrets
  namespace: gitlab
type: Opaque
data:
  password: {{ required "gitlab.postgresql.password is required" .Values.gitlab.postgresql.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis-secret
  namespace: gitlab
type: Opaque
data:
  redis-password: {{ required "gitlab.redis.password is required" .Values.gitlab.redis.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-rails-storage
  namespace: gitlab
type: Opaque
data:
  connection: {{ required "gitlab.storage.connection is required" .Values.gitlab.storage.connection | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-smtp-secret
  namespace: gitlab
type: Opaque
data:
  password: {{ "Prisma$2026?" | b64enc | quote }}
{{- end }}
---
{{- if .Values.nexus }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-password
  namespace: nexus
type: Opaque
data:
  password: {{ required "nexus.postgres.password is required" .Values.nexus.postgres.password | b64enc }}
{{- end }}