defaultStorageClass: longhorn
installed:
  ingressNginx: true
  certManager: true
  rancher: true
  metalLB: true
  longhorn: true
  loki: true
  prometheusStack: true
  rabbitMQ: true
  redis: true
  mongoDB: false
  datadog: false
  nifi: true
  camunda: true
  tika: true
  nifikop: true
  keycloak: true
  harbor: true
  elastic: false
  apisix: true
loadBalancerIpRange:
  start: 10.32.11.50
  end: 10.32.11.60
longhorn:
  volumeReplica: 1
keycloak:
  externalDatabase:
    host: "postgresql-prd.pcdacs.local"
    port: 5000
    user: admin
    password: password
    database: keycloak