defaultStorageClass: standard
installed:
  ingressNginx: true
  certManager: true
  rancher: true
  metalLB: true
  longhorn: true
  loki: true
  prometheusStack: true
  rabbitMQ: true
  redis: true
  mongoDB: true
  datadog: false
  nifi: true
  camunda: true
  tika: true
  nifikop: true
  keycloak: true
  harbor: true
  wso2: true
  sonarqube: true