defaultStorageClass: longhorn
installed:
  ingressNginx: true
  certManager: true
  rancher: true
  metalLB: true
  longhorn: true
  loki: true
  prometheusStack: true
  rabbitMQ: true
  redis: true
  mongoDB: true
  datadog: false
  nifi: true
  camunda: true
  nifikop: true
  keycloak: false
  harbor: false
  elastic: true
  apisix: true
loadBalancerIpRange:
  start: 10.11.0.50
  end: 10.11.0.60
longhorn:
  volumeReplica: 1
keycloak:
  externalDatabase:
    host: "10.2.0.11"
    port: 5432
    user: postgres
    password: password
    database: keycloak