defaultStorageClass: longhorn
installed:
  ingressNginx: true
  certManager: true
  rancher: true
  metalLB: true
  longhorn: true
  loki: true
  prometheusStack: true
  rabbitMQ: true
  redis: true
  mongoDB: true
  datadog: false
  nifi: true
  camunda: true
  tika: true
  nifikop: true
  keycloak: false
  harbor: true
  wso2: true
  sonarqube: true
loadBalancerIpRange:
  start: 10.32.1.50
  end: 10.32.1.60
longhorn:
  volumeReplica: 1