defaultStorageClass: standard
installed:
  ingressNginx: true
  certManager: true
  metalLB: false
  istio: false
  kiali: false
  longhorn: false
  loki: false
  prometheusStack: false
  jaeger: false
  opentelemetry: false
  rabbitMQ: false
  redis: false
  mongoDB: false
  minio: true
  datadog: false
  nifi: false
  camunda: false
  tika: true
  nifikop: false
  keycloak: true