{{- if .Values.datadog.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: datadog
type: Opaque
data:
  api-key: {{ .Values.datadog.credentials.apiKey }}

---

kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
  namespace: datadog
spec:
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    liveProcessCollection:
      enabled: false
    liveContainerCollection:
      enabled: true
    apm:
      enabled: true
      instrumentation:
        enabled: true
        enabledNamespaces:
          {{- range .Values.datadog.apm.enabledNamespaces }}
          - {{ . }}
          {{- end }}
    cspm:
      enabled: false
    cws:
      enabled: false
    npm:
      enabled: false
    admissionController:
      enabled: true
      mutateUnlabelled: false
    externalMetricsServer:
      enabled: false
      useDatadogMetrics: false
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    clusterName: {{ .Values.datadog.clusterName }}
    site: datadoghq.eu
    tags:
      {{- range .Values.datadog.tags }}
      - {{ . }}
      {{- end }}
    kubelet:
      tlsVerify: false
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoExecute
{{- end }}