{{- if .Values.metallb.enabled }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.metallb.ipAddressPool.name }}
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.metallb.ipAddressPool.ipRange.start }}-{{ .Values.metallb.ipAddressPool.ipRange.end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - {{ .Values.metallb.ipAddressPool.name }}
  autoAssign: true
{{- end }}