initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.10.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
        
configuration:
  features: EnableCSI
  defaultVolumesToFsBackup: true
  backupStorageLocation:
  - name: minio
    provider: aws
    bucket: k8s-devops
    accessMode: ReadWrite
    default: true
    config:
      region: us-east-1
      s3ForcePathStyle: true
      s3Url: https://minio-api-dev.pcdacs.local
      publicUrl: https://minio-api-dev.pcdacs.local
      # s3Url: https://pcd-dv-minio-c01.pcdacs.local:9000
      # publicUrl: https://pcd-dv-minio-c01.pcdacs.local:9000
  volumeSnapshotLocation:
  - name: minio
    provider: aws
    config:
      region: us-east-1
      
credentials:
  useSecret: true
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = admin
      aws_secret_access_key = 873hasjdh1xV1ejkHsaLpA
    # cloud: |
    #   [default]
    #   aws_access_key_id = minioadmin
    #   aws_secret_access_key = 873hasjdh1xV1ejkHsaLpA
deployNodeAgent: true