apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secrets
  namespace: gitlab
type: Opaque
data:
  password: Z2l0bGFi #gitlab
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis-secret
  namespace: gitlab
type: Opaque
data:
  redis-password: amZLRUZPRXd5Rg== #jfKEFOEwyF
