metallb:
  enabled: true
  ipAddressPool:
    name: default-pool
    ipRange:
      start: 10.1.0.50
      end: 10.1.0.60

datadog:
  enabled: true
  clusterName: adarte
  credentials:
    apiKey: "8f90dfc3d260ce1975271fd65d8f7570"
  apm:
    enabledNamespaces:
      - adarte-prod-integration
      - adarte-prod-portal-be
      - adarte-prod-cms-web
      - adarte-prod-batch
      - adarte-prod-cca-be
  tags:
    - env:prod

rabbitMQ:
  enabled: true

nifi:
  nodes: 2
  enabled: true

secretpullnamespaces:
  - default

environment: dev

minIOproxy:
  address: 10.3.0.11
  enabled: true

createRoleForDevelopers:
  enabled: true

apisix:
  enabled: true