apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-test-api
  template:
    metadata:
      labels:
        app: flask-test-api
    spec:
      containers:
        - name: flask-test-api
          image: aptul9/flask-test-api:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-test-api-service
spec:
  selector:
    app: flask-test-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
