kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
  namespace: datadog
spec:
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
    liveProcessCollection:
      enabled: false
    liveContainerCollection:
      enabled: true
    apm:
      enabled: true
      instrumentation:
        enabled: true
        enabledNamespaces:
          - gitlab
          - harbor
          - nexus
    cspm:
      enabled: false
    cws:
      enabled: false
    npm:
      enabled: false
    admissionController:
      enabled: true
      mutateUnlabelled: false
    externalMetricsServer:
      enabled: false
      useDatadogMetrics: false
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    clusterName: adarte
    site: datadoghq.eu
    tags:
      - env:acs_devops
    kubelet:
      tlsVerify: false
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      env:
        - name: DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION
          value: "true"
        - name: DD_CONTAINER_EXCLUDE
          value: "kube_namespace:adarte-prod-batch kube_namespace:glusterfs-app kube_namespace:wso2"
#          value: "kube_namespace:adarte-prod-integration kube_namespace:glusterfs-app kube_namespace:wso2 kube_namespace:adarte-prod-portal-be" 
      image:
        name: gcr.io/datadoghq/agent:latest
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoExecute
        - key: app
          operator: Equal
          value: ingress
          effect: NoSchedule