defaultStorageClass: longhorn
installed:
  ingressNginx: true
  certManager: true
  rancher: true
  metalLB: true
  longhorn: true
  loki: true
  prometheusStack: true
  rabbitMQ: true
  redis: true
  mongoDB: true
  datadog: false
  nifi: true
  camunda: true
  nifikop: true
  keycloak: true
  harbor: false
  elastic: true
  apisix: true
  minIOproxy: false
loadBalancerIpRange:
  start: 10.11.0.50
  end: 10.11.0.60
subNet: 10.11.0
longhorn:
  volumeReplica: 1
keycloak:
  externalDatabase:
    host: "10.2.0.11"
    port: 5432
    user: keycloak
    password: keycloak
    database: keycloak_int