apiVersion: v1
kind: Secret
metadata:
  name: my-ca-secret
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Get "cert/ca.crt") | b64enc }}
  tls.key: {{ (.Files.Get "cert/ca.key") | b64enc }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-internal-ca
spec:
  ca:
    secretName: my-ca-secret
