apiVersion: v1
kind: Secret
metadata:
  name: my-ca-secret
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: {{ (.Files.Get "cert/ca.crt") | b64enc }}
  tls.key: {{ (.Files.Get "cert/ca.key") | b64enc }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-internal-ca
spec:
  ca:
    secretName: my-ca-secret
---
{{- if eq .Values.environment "prd" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-prd
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}