{{- if .Values.createRoleForDevelopers.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-readonly
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-user
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer-readonly
subjects:
- kind: ServiceAccount
  name: developer-user
  namespace: kube-system

---
apiVersion: v1
kind: Secret
metadata:
  name: developer-user-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: developer-user
type: kubernetes.io/service-account-token
{{- end }}