# https://github.com/konpyutaika/nifikop/blob/master/config/samples/http_nificluster.yaml
{{- if .Values.nifi.enabled }}
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifikop
  namespace: nifi
spec:
  {{- $nodeCount := .Values.nifi.nodes | default 1 | int -}}
  {{- if lt $nodeCount 1 -}}
    {{- fail "nifi.nodes must be greater than or equal to 1" -}}
  {{- end }}
  clusterImage: apache/nifi:2.5.0
  nodeUserIdentityTemplate: node-%d-nifikop
  externalServices:
    - name: nifikop
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8080
          - internalListenerName: s2s
            port: 10000
        type: LoadBalancer
  listenersConfig:
    internalListeners:
      - containerPort: 8080
        name: http
        type: http
      - containerPort: 6007
        name: cluster
        type: cluster
      - containerPort: 10000
        name: s2s
        type: s2s
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  managedAdminUsers:
    - identity: juldrixx@gmail.com
      name: jguitton
  nodeConfigGroups:
    default_group:
      fsGroup: 1337
      isNode: true
      resourcesRequirements:
        limits:
          cpu: "4"
          memory: 3Gi
        requests:
          cpu: "4"
          memory: 2Gi
      serviceAccountName: nifikop-cluster
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - mountPath: /opt/nifi/data
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - mountPath: /opt/nifi/flowfile_repository
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - mountPath: /opt/nifi/nifi-current/conf
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - mountPath: /opt/nifi/content_repository
          name: content-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - mountPath: /opt/nifi/provenance_repository
          name: provenance-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
        - mountPath: /opt/nifi/extensions
          name: extensions-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  nodes:
    {{- range $i := until $nodeCount }}
    - id: {{ $i }}
      labels:
        nifi_cr: nifikop
        nifi_node_group: default_group
      nodeConfigGroup: default_group
    {{- end }}
  propagateLabels: false
  readOnlyConfig:
    bootstrapProperties:
      nifiJvmMemory: 3g
      overrideConfigs: |
        java.arg.7=-XX:ReservedCodeCacheSize=256m
        java.arg.8=-XX:+UseCodeCacheFlushing
    maximumTimerDrivenThreadCount: 40
    nifiProperties:
      overrideConfigs: |
        nifi.nar.library.autoload.directory=../extensions
        nifi.sensitive.props.key=nifikopnifikopnifikop
      webProxyHosts:
        - nifi-{{ .Values.environment }}.pcdacs.local:8080
        - nifi-{{ .Values.environment }}.pcdacs.local
  service:
    headlessEnabled: true
  sidecarConfigs:
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-app.log
      image: busybox:1.36
      name: app-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-bootstrap.log
      image: busybox:1.36
      name: bootstrap-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-user.log
      image: busybox:1.36
      name: user-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
  clusterManager: kubernetes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifikop
  namespace: nifi
  annotations:
    nginx.org/ssl-services: nifikop
    nginx.org/lb-method: ip_hash
    cert-manager.io/cluster-issuer: "internal-ca"
spec:
  ingressClassName: nginx
  rules:
    - host: nifi-{{ .Values.environment }}.pcdacs.local
      http:
        paths:
          - backend:
              service:
                name: nifikop
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - nifi-{{ .Values.environment }}.pcdacs.local
      secretName: nifi-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifikop-cluster
  namespace: nifi
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifi
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifi
subjects:
  - kind: ServiceAccount
    name: nifikop-cluster
    namespace: nifi
roleRef:
  kind: Role
  name: nifikop-cluster
  apiGroup: rbac.authorization.k8s.io
{{- end }}