# questo è solo un esempio, ricordarsi di modificarlo a seconda degli URL dei vari ambienti
{{- range .Values.secretpullnamespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: harborpullsecret
  namespace: {{ . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ `{"auths":{"harbor.local":{"username":"admin","password":"jfKEFOwyF"}}}` | b64enc | quote }}
{{- end }}