{{- if .Values.rabbitMQ.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: rabbit
---
# kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbit
spec:
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  persistence:
    storageClassName: longhorn
    storage: "5Gi"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-dashboard-ingress
  namespace: rabbit
  annotations:
    cert-manager.io/cluster-issuer: "internal-ca"
spec:
  ingressClassName: nginx
  rules:
  - host: rabbitmq-console-{{ .Values.environment }}.pcdacs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-cluster
            port:
              number: 15672
  tls:
    - hosts:
        - rabbitmq-console-{{ .Values.environment }}.pcdacs.local
      secretName: rabbitmq-management-tls
{{- end }}