# Example configuration of `connection` secret for Rails
# Example for Minio storage
#   See https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/charts/globals.md#connection
#   See https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/advanced/external-object-storage
provider: AWS
# Specify the region
region: us-east-1
# Specify access/secret keys
aws_access_key_id: minioadmin
aws_secret_access_key: minioadmin123
# The below settings are for S3 compatible endpoints
#   See https://docs.gitlab.com/administration/object_storage/#amazon-s3
aws_signature_version: 4
host: "10.186.0.121"
endpoint: "https://10.186.0.121:9000"
path_style: true


# kubectl create secret generic gitlab-rails-storage --from-file=connection=minio-secret.yaml -n gitlab
